In [1]:
import os
import csv
import numpy as np
import netCDF4 as nc

In [2]:
base_dir = r'F:\Study\santa-close-ai\data-preprocess-hub\data\fuel\raw'

dfmc_dir = 'DFMC'
fuel_dir = 'FUEL'
lfmc_dir = 'LFMC'

dfmc_file = 'DFMC_MAP_2021_12.area-subset.39.132.33.124.nc'
fuel_file = 'FUEL_MAP_2021_12.area-subset.39.132.33.124.nc'
lfmc_file = 'LFMC_MAP_2021_12.area-subset.39.132.33.124.nc'

In [3]:
dfmc_path = os.path.join(base_dir, dfmc_dir, dfmc_file)
dfmc_path

'F:\\Study\\santa-close-ai\\data-preprocess-hub\\data\\fuel\\raw\\DFMC\\DFMC_MAP_2021_12.area-subset.39.132.33.124.nc'

In [4]:
fuel_path = os.path.join(base_dir, fuel_dir, fuel_file)
fuel_path

'F:\\Study\\santa-close-ai\\data-preprocess-hub\\data\\fuel\\raw\\FUEL\\FUEL_MAP_2021_12.area-subset.39.132.33.124.nc'

In [5]:
lfmc_path = os.path.join(base_dir, lfmc_dir, lfmc_file)
lfmc_path

'F:\\Study\\santa-close-ai\\data-preprocess-hub\\data\\fuel\\raw\\LFMC\\LFMC_MAP_2021_12.area-subset.39.132.33.124.nc'

In [6]:
if os.path.exists(dfmc_path):
    print("DFMC Exists : {}".format(dfmc_path))

if os.path.exists(fuel_path):
    print("FUEL Exists : {}".format(fuel_path))

if os.path.exists(lfmc_path):
    print("LFMC Exists : {}".format(lfmc_path))

DFMC Exists : F:\Study\santa-close-ai\data-preprocess-hub\data\fuel\raw\DFMC\DFMC_MAP_2021_12.area-subset.39.132.33.124.nc
FUEL Exists : F:\Study\santa-close-ai\data-preprocess-hub\data\fuel\raw\FUEL\FUEL_MAP_2021_12.area-subset.39.132.33.124.nc
LFMC Exists : F:\Study\santa-close-ai\data-preprocess-hub\data\fuel\raw\LFMC\LFMC_MAP_2021_12.area-subset.39.132.33.124.nc


In [7]:
dfmc_data = nc.Dataset(dfmc_path)
dfmc_data

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    CDI: Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)
    Conventions: CF-1.6
    CDO: Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)
    history: Tue Nov 26 22:06:58 2024: ncatted -O -a standard_name,time,c,c,time -a calendar,time,c,c,standard -a axis,time,c,c,T -a units,lon,m,c,degrees_east -a axis,lon,c,c,X -a units,lat,m,c,degrees_north -a axis,lat,c,c,Y -a missing_value,DFMC_Wood,c,f,nan -a missing_value,DFMC_Foliage,c,f,nan tmp_unlimx.nc /ec/vol/cems_fire/FUEL_DATA/ECMWF-Fuel-Characteristics_V1/Fuel-Moisture/Dead/2021/DFMC_MAP_2021_12.nc
Tue Nov 26 22:06:02 2024: cdo mulc,100 tmpx.nc tmp_unlimx.nc
Tue Nov 26 22:05:22 2024: cdo -f nc4c -setreftime,2021-12-01,00:00:00,1day /ec/vol/centaur/pajm/DATA/DFMC_MAP_2021_12.nc tmpx.nc
    NCO: netCDF Operators version 5.1.9 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco, Citation = 10.1016/j.envsoft.2008.03.004

In [8]:
fuel_data = nc.Dataset(fuel_path)
fuel_data

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    CDI: Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)
    Conventions: CF-1.6
    CDO: Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)
    history: Wed Dec  4 18:16:05 2024: ncatted -O -a standard_name,time,c,c,time -a calendar,time,c,c,standard -a axis,time,c,c,T -a units,lon,m,c,degrees_east -a axis,lon,c,c,X -a units,lat,m,c,degrees_north -a axis,lat,c,c,Y -a missing_value,Live_Leaf,c,f,nan -a missing_value,Live_Wood,c,f,nan -a missing_value,Dead_Foliage,c,f,nan -a missing_value,Dead_Wood,c,f,nan tmp_unlim.nc /ec/vol/cems_fire/FUEL_DATA/ECMWF-Fuel-Characteristics_V1/Fuel-Load/2021/FUEL_MAP_2021_12.nc
Wed Dec 04 18:13:38 2024: cdo -f nc4c -setreftime,2021-12-01,00:00:00,1day /ec/vol/centaur/pajm/DATA/TV_CFUEL_CORRECTED_MAP_2021_12.nc tmp_unlim.nc
    NCO: netCDF Operators version 5.1.9 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco, Citation = 10.1016/j.e

In [9]:
lfmc_data = nc.Dataset(lfmc_path)
lfmc_data

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    CDI: Climate Data Interface version 2.4.0 (https://mpimet.mpg.de/cdi)
    Conventions: CF-1.6
    CDO: Climate Data Operators version 2.4.0 (https://mpimet.mpg.de/cdo)
    history: Tue Nov 26 21:29:44 2024: ncatted -O -a standard_name,time,c,c,time -a calendar,time,c,c,standard -a axis,time,c,c,T -a units,lon,m,c,degrees_east -a axis,lon,c,c,X -a units,lat,m,c,degrees_north -a axis,lat,c,c,Y -a missing_value,LFMC,c,f,nan -a missing_value,LFMC_low,c,f,nan -a missing_value,LFMC_high,c,f,nan tmpy.nc /ec/vol/cems_fire/FUEL_DATA/ECMWF-Fuel-Characteristics_V1/Fuel-Moisture/Live/2021/LFMC_MAP_2021_12.nc
Tue Nov 26 21:28:02 2024: cdo -f nc4c -setreftime,2021-12-01,00:00:00,1day /ec/vol/centaur/pajm/DATA/LFMC_MAP_2021_12.nc tmpy.nc
    NCO: netCDF Operators version 5.1.9 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco, Citation = 10.1016/j.envsoft.2008.03.004)
    dimensions(sizes): time(31), lat(86

In [10]:
dfmc_lon = dfmc_data['lon'][:].data
dfmc_lon

array([124.06542056, 124.13551402, 124.20560748, 124.27570093,
       124.34579439, 124.41588785, 124.48598131, 124.55607477,
       124.62616822, 124.69626168, 124.76635514, 124.8364486 ,
       124.90654206, 124.97663551, 125.04672897, 125.11682243,
       125.18691589, 125.25700935, 125.3271028 , 125.39719626,
       125.46728972, 125.53738318, 125.60747664, 125.67757009,
       125.74766355, 125.81775701, 125.88785047, 125.95794393,
       126.02803738, 126.09813084, 126.1682243 , 126.23831776,
       126.30841121, 126.37850467, 126.44859813, 126.51869159,
       126.58878505, 126.6588785 , 126.72897196, 126.79906542,
       126.86915888, 126.93925234, 127.00934579, 127.07943925,
       127.14953271, 127.21962617, 127.28971963, 127.35981308,
       127.42990654, 127.5       , 127.57009346, 127.64018692,
       127.71028037, 127.78037383, 127.85046729, 127.92056075,
       127.99065421, 128.06074766, 128.13084112, 128.20093458,
       128.27102804, 128.3411215 , 128.41121495, 128.48

In [11]:
dfmc_lat = dfmc_data['lat'][:].data
dfmc_lat

array([38.98066695, 38.91036819, 38.84006942, 38.76977065, 38.69947188,
       38.62917312, 38.55887435, 38.48857558, 38.41827681, 38.34797805,
       38.27767928, 38.20738051, 38.13708174, 38.06678298, 37.99648421,
       37.92618544, 37.85588667, 37.78558791, 37.71528914, 37.64499037,
       37.5746916 , 37.50439283, 37.43409407, 37.3637953 , 37.29349653,
       37.22319776, 37.152899  , 37.08260023, 37.01230146, 36.94200269,
       36.87170393, 36.80140516, 36.73110639, 36.66080762, 36.59050886,
       36.52021009, 36.44991132, 36.37961255, 36.30931378, 36.23901502,
       36.16871625, 36.09841748, 36.02811871, 35.95781995, 35.88752118,
       35.81722241, 35.74692364, 35.67662487, 35.60632611, 35.53602734,
       35.46572857, 35.3954298 , 35.32513104, 35.25483227, 35.1845335 ,
       35.11423473, 35.04393596, 34.9736372 , 34.90333843, 34.83303966,
       34.76274089, 34.69244213, 34.62214336, 34.55184459, 34.48154582,
       34.41124705, 34.34094829, 34.27064952, 34.20035075, 34.13

In [12]:
dfmc_time = dfmc_data['time'][:].data
dfmc_time

array([ 0.5       ,  1.47916667,  2.47916667,  3.47916667,  4.47916667,
        5.47916667,  6.47916667,  7.47916667,  8.47916667,  9.47916667,
       10.47916667, 11.47916667, 12.47916667, 13.47916667, 14.47916667,
       15.47916667, 16.47916667, 17.47916667, 18.47916667, 19.47916667,
       20.47916667, 21.47916667, 22.47916667, 23.47916667, 24.47916667,
       25.47916667, 26.47916667, 27.47916667, 28.47916667, 29.47916667,
       30.47916667])

In [13]:
fuel_lon = fuel_data['lon'][:].data
fuel_lon

array([124.06542 , 124.13551 , 124.205605, 124.2757  , 124.345795,
       124.415886, 124.485985, 124.556076, 124.62617 , 124.69626 ,
       124.76636 , 124.83645 , 124.90654 , 124.97664 , 125.04673 ,
       125.11682 , 125.18691 , 125.25701 , 125.3271  , 125.397194,
       125.46729 , 125.537384, 125.607475, 125.67757 , 125.747665,
       125.81776 , 125.88785 , 125.95795 , 126.02804 , 126.09813 ,
       126.16822 , 126.23832 , 126.30841 , 126.3785  , 126.4486  ,
       126.51869 , 126.58878 , 126.65888 , 126.72897 , 126.799065,
       126.869156, 126.939255, 127.009346, 127.07944 , 127.149536,
       127.21963 , 127.28972 , 127.35981 , 127.42991 , 127.5     ,
       127.57009 , 127.64019 , 127.71028 , 127.78037 , 127.850464,
       127.92056 , 127.990654, 128.06075 , 128.13084 , 128.20093 ,
       128.27103 , 128.34113 , 128.41121 , 128.48131 , 128.5514  ,
       128.62149 , 128.69159 , 128.76169 , 128.83177 , 128.90187 ,
       128.97197 , 129.04205 , 129.11215 , 129.18224 , 129.252

In [14]:
fuel_lat = fuel_data['lat'][:].data
fuel_lat

array([38.980667, 38.91037 , 38.84007 , 38.76977 , 38.69947 , 38.629173,
       38.558876, 38.488575, 38.418278, 38.347977, 38.27768 , 38.207382,
       38.13708 , 38.066784, 37.996483, 37.926186, 37.85589 , 37.785587,
       37.71529 , 37.64499 , 37.57469 , 37.504395, 37.434093, 37.363796,
       37.293495, 37.223198, 37.1529  , 37.0826  , 37.012302, 36.942   ,
       36.871704, 36.801407, 36.731106, 36.66081 , 36.590508, 36.52021 ,
       36.449913, 36.379612, 36.309315, 36.239014, 36.168716, 36.09842 ,
       36.02812 , 35.95782 , 35.88752 , 35.817223, 35.746925, 35.676624,
       35.606327, 35.536026, 35.46573 , 35.39543 , 35.32513 , 35.254833,
       35.184532, 35.114235, 35.043938, 34.973637, 34.90334 , 34.83304 ,
       34.76274 , 34.692444, 34.622143, 34.551846, 34.481544, 34.411247,
       34.34095 , 34.27065 , 34.20035 , 34.13005 , 34.059753, 33.989456,
       33.919155, 33.848858, 33.778557, 33.70826 , 33.637962, 33.56766 ,
       33.497364, 33.427063, 33.356766, 33.28647 , 

In [15]:
fuel_time = fuel_data['time'][:].data
fuel_time

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ,
       1.04166667, 1.08333333, 1.125     , 1.16666667, 1.20833333,
       1.25      ])

In [16]:
lfmc_lon = lfmc_data['lon'][:].data
lfmc_lon

array([124.06542056, 124.13551402, 124.20560748, 124.27570093,
       124.34579439, 124.41588785, 124.48598131, 124.55607477,
       124.62616822, 124.69626168, 124.76635514, 124.8364486 ,
       124.90654206, 124.97663551, 125.04672897, 125.11682243,
       125.18691589, 125.25700935, 125.3271028 , 125.39719626,
       125.46728972, 125.53738318, 125.60747664, 125.67757009,
       125.74766355, 125.81775701, 125.88785047, 125.95794393,
       126.02803738, 126.09813084, 126.1682243 , 126.23831776,
       126.30841121, 126.37850467, 126.44859813, 126.51869159,
       126.58878505, 126.6588785 , 126.72897196, 126.79906542,
       126.86915888, 126.93925234, 127.00934579, 127.07943925,
       127.14953271, 127.21962617, 127.28971963, 127.35981308,
       127.42990654, 127.5       , 127.57009346, 127.64018692,
       127.71028037, 127.78037383, 127.85046729, 127.92056075,
       127.99065421, 128.06074766, 128.13084112, 128.20093458,
       128.27102804, 128.3411215 , 128.41121495, 128.48

In [17]:
lfmc_lat = lfmc_data['lat'][:].data
lfmc_lat

array([38.98066695, 38.91036819, 38.84006942, 38.76977065, 38.69947188,
       38.62917312, 38.55887435, 38.48857558, 38.41827681, 38.34797805,
       38.27767928, 38.20738051, 38.13708174, 38.06678298, 37.99648421,
       37.92618544, 37.85588667, 37.78558791, 37.71528914, 37.64499037,
       37.5746916 , 37.50439283, 37.43409407, 37.3637953 , 37.29349653,
       37.22319776, 37.152899  , 37.08260023, 37.01230146, 36.94200269,
       36.87170393, 36.80140516, 36.73110639, 36.66080762, 36.59050886,
       36.52021009, 36.44991132, 36.37961255, 36.30931378, 36.23901502,
       36.16871625, 36.09841748, 36.02811871, 35.95781995, 35.88752118,
       35.81722241, 35.74692364, 35.67662487, 35.60632611, 35.53602734,
       35.46572857, 35.3954298 , 35.32513104, 35.25483227, 35.1845335 ,
       35.11423473, 35.04393596, 34.9736372 , 34.90333843, 34.83303966,
       34.76274089, 34.69244213, 34.62214336, 34.55184459, 34.48154582,
       34.41124705, 34.34094829, 34.27064952, 34.20035075, 34.13

In [18]:
lfmc_time = lfmc_data['time'][:].data
lfmc_time

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5,
       22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5])